name: Producer CI Pipeline

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  producer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Check environment
        run: |
          python3 --version
          aws --version

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v5
        with:
          role-to-assume: arn:aws:iam::<ACCOUNT-ID>:role/test-env1-producer
          aws-region: us-west-2

      - name: Verify AWS identity
        run: aws sts get-caller-identity

      - name: Run producer
        run: python3 producer.py